name: ci
on:
  push:
    branches:
      - feature/gha
      - master
  pull_request:
    branches:
      - feature/gha

env:
  RUN_SECURITY_CHECK: ${{ github.base_ref == 'feature/gha' }}

jobs:
  echo-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run echo
        if: fromJSON(env.RUN_SECURITY_CHECK)
        run: echo "running security checks"
